---
# This task set the file /etc/tangorc from the variable {{tango_host}}
# Tango
- name: ensure OpenJDK is present (needed for both client and server)
  yum: pkg=java-1.7.0-openjdk state=latest

- name: ensure the Tango Base packages are present
  yum: pkg=tango-common state=latest
  tags:
    - TANGO_HOST

- name: ensure the PyTango  packages is present
  yum: pkg={{ item }} state=latest
  with_items:
    - python-pytango
#    - python-dsconfig

# test: json2tango -o -d -v -w ~/.tango/hdb.json
- name: ensure the Tango dsconfig packages is present
  yum: pkg={{ item }} state=present
  with_items:
#    - python-dsconfig
    - python-dsconfig-1.1.1-1.el7.centos.maxlab

- name: ensure Tango Host is correctly configured
  template: src=tangorc dest=/etc/tangorc owner=root group=root mode=0644
  tags:
    - TANGO_HOST
  notify:
  - tango_host has changed
