---
galaxy_info:
  author: Atsushi Sasaki
  description: NFS installation and setup
  license: license (BSD)
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - 6
  - name: Ubuntu
    versions:
    - precise
  categories:
  - system
dependencies: []
