---
#Set up network interface eth1
- name: set up network interface eth1
  template: src=ifcfg-eth1 dest=/etc/sysconfig/network-scripts/ owner=root group=root mode=644
  notify: restart eth1
- name: set up network gateway for eth1
  template: src=route-eth1 dest=/etc/sysconfig/network-scripts/ owner=root group=root mode=644
  notify: restart eth1
