---
- debug: var=java_oracle

- name: Install the Oracle Java Runtime Environment
  yum: name=wget state=present
  when: network=='public'

- name: Check if the correct java version is installeA
  stat: path=/usr/java/{{ java_oracle.rpm.version }}/bin/java
  register: st

#Test

#/Test

- name: Download the Oracle Java RPM
  #shell: 'wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" {{ java_oracle.rpm.base_url}}{{ java_oracle.rpm.name }}'
  shell: 'wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.rpm" '
  #get_url: 'validate_certs=no  --no-cookies headers="Cookie\: oraclelicense=accept-securebackup-cookie" url={{ java_oracle.rpm.base_url}}{{ java_oracle.rpm.name }}'
  when: network=='public' and st.stat.exists==False

- name: Install the Oracle Java Runtime Environment
  yum: name=./{{ java_oracle.rpm.name }} state=present
  when: network=='public' and st.stat.exists==False

- name: Use Oracle Java
  alternatives: name=java link=/usr/bin/java path=/usr/java/{{ java_oracle.rpm.version }}/bin/java
  when: network=='public'

- name: Install the Oracle Java Runtime Environment
  yum: name=http://{{ repo_server }}/control/java/jre-8u45-linux-x64.rpm state=present
  when: network=='private'

- name: Use Oracle Java
  alternatives: name=java link=/usr/bin/java path=/usr/java/jre1.8.0_45/bin/java
  when: network=='private'
