---
- name: Install the GNOME Desktop packages
  yum: name="@GNOME Desktop" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6

- name: Install the Gnome Desktop environment packages
  yum: name="@^gnome-desktop-environment" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

- name: Install the Mate Desktop environment packages
  yum: name="@^gnome-desktop-environment" state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7 and mate_desktop is defined

- name: Install the Desktop Extension packages
  yum: name="{{ item }}" state=present disablerepo=elrepo
  with_items:
    - "@X Window System"
    - "@Desktop"
    - "@Desktop Platform"
    - "@Fonts"
    - "@Graphical Administration Tools"
    - "@Internet Browser"
    - "@General Purpose Desktop"
    - "@Office Suite and Productivity"
    - "@Graphics Creation Tools"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6

- name: Install the Desktop Extension packages
  yum: name="{{ item }}" state=present
  with_items:
    - "gnome-shell-extension-workspace-indicator"
    - "gnome-shell-extension-panel-favorites"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 7

- name: Make sure the OS start with the desktop
  lineinfile: dest=/etc/inittab regexp='^id:\d:initdefault:$' line='id:5:initdefault:'
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6
  tags:
    - debug

- name: Make sure the OS start with the desktop
  command: systemctl get-default
  register: st
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
  changed_when: false
  tags:
    - debug
- debug: var=st
  tags:
    - debug

- name: Make sure the OS start with the desktop
  command: systemctl set-default graphical.target
  when: st.stdout != "graphical.target" and ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
  tags:
    - debug
