---
json_file: "/tmp/archiving.json"
tdb:
  server: "TdbArchiver"
  clazz: "TdbArchiver"
  instances:
    - "01"
    - "02"
    - "03"
    - "04"
    - "05"
    - "06"
    - "07"
    - "08"
    - "09"
    - "10"
    - "11"
    - "12"
    - "13"
    - "14"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
  device_per_instance: 5
hdb:
  server: "HdbArchiver"
  clazz: "HdbArchiver"
  number_of_instances: 40
  instances:
    - "01"
    - "02"
    - "03"
    - "04"
    - "05"
    - "06"
    - "07"
    - "08"
    - "09"
    - "10"
    - "11"
    - "12"
    - "13"
    - "14"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
  device_per_instance: 5
snap:
  xml_file: "beansMAXIV.xml"
