---
- name: Make sure all local groups exist
  group: name={{ item.1 }}
  #with_items: users
  with_subelements:
     - accounts
     - groups
  when: accounts is defined
 
- name: Make sure the user exists 
  user: name={{ item.name }} shell=/bin/zsh groups={{ item.groups|join(',') }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa password={{ item.password }}
  with_items: accounts
  notify:
    - restart sshd

#- name: Add the User to the Authorized Key
#  authorized_key: user={{ item.name }} key="{{ item.id }}"
#  with_items: accounts
