---
# This role manage the settings of the network home directory
- name: ensure the CLS packages are present
  yum: pkg={{ item }} state=latest
  with_items:
    - nfs-utils

# Ensure rpcbind is runnning
- name: Ensure rpcbind is running
  service: name=rpcbind state=started enabled=yes

  
# NFS Server configuration
# VINHAR: Can probably automated but let's KISS
#- name: ensure the computer has access to the NFS server
#  lineinfile: 
#    dest: /etc/exports
#    insertafter: '/mxn/home'
#    line: '		{{ ansible_default_ipv4.address }}(rw,no_subtree_check)\'
#    regexp: '{{ ansible_default_ipv4.address }}'
#    backup: yes
#  delegate_to: "{{ nfs_server }}"
#  notify:
#    - reload nfs-kernel-server

# Force the reload of the nfs server if necessary
#- meta: flush_handlers


# NFS HOME
# The mount point should be created by the mount module
#- name: ensure the NFS mount dir exists
#  file: path={{ item.path }} state=directory
#        owner='{{ item.owner|default(nfs_default_owner) }}'
#        group='{{ item.group|default(nfs_default_group) }}'
#        mode='{{ item.mode|default("0777") }}'
#  with_items: nfs_mounted_directories
#  ignore_errors: yes

- name: ensure the NFS dir is mounted
  mount: name={{ item.path }} src={{ item.server.host }}:{{ item.server.path }} fstype=nfs opts={{ item.options|default([])|join(",") }} state=mounted
  with_items: nfs_mounted_directories

